// <auto-generated />
using AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSTarjetas.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20241223144551_InitialCreateCuentas")]
    partial class InitialCreateCuentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modelos.Tarjeta", b =>
                {
                    b.Property<int>("idTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTarjeta"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTarjeta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoTarjeta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("idTarjeta");

                    b.ToTable("Tarjetas");

                    b.HasData(
                        new
                        {
                            idTarjeta = 1,
                            IdCliente = 1,
                            NumeroTarjeta = "5897 8525 4569 4521",
                            TipoTarjeta = "Master Card"
                        },
                        new
                        {
                            idTarjeta = 2,
                            IdCliente = 1,
                            NumeroTarjeta = "6985 3247 4569 7852",
                            TipoTarjeta = "Visa"
                        },
                        new
                        {
                            idTarjeta = 3,
                            IdCliente = 2,
                            NumeroTarjeta = "3697 1497 6347 2674",
                            TipoTarjeta = "American Express"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
